# Site
repository: angelaguayo/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alberto Angel Aguayo Perez
title: Computer Sciences Engineer
email: anggelagguayoo@gmail.com
website: www.github.com/angelaguayo/resume

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: anggelagguayoo
github_username:  angelaguayo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: anggelagguayoo
# linkedin_username: alberto angel aguayo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Alberto Angel Aguayo, I'm been working in IT about 5 years.

  I am most skilled in: <mark>Linux</mark> and <mark>Eating Tacos</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: school door bot
        #link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  angelaguayo/porton
            icon: fab fa-github
            url: github.com/angelaguayo
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          i'm really proud of myself to do that, I think is unique 
        description: | # this will include new lines to allow paragraphs
          I started that project without knowledge about that, so I was doing sted by step, is about of a telegram bot, written on python with 2 technologies more that are IFTTT(if this then that) is about of home automation and Internet of Things and a little device from sonoff ewelink, so this bot is programmed to send a signal between CURL to activate the school's door

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad Pedagogica Nacional
        link: https://upn.mx/
        # link_text: boringcompany.com
        sub_title: Technology Manager
        caption: junuary 2018 - Present
        quote: >
          Solving problems about network, computers, printer, and Scholar server
        description: | # this will include new lines to allow paragraphs
            was a new vacant when I completed my studies, so i was the first engineer here.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Guadalajara
        caption: 2010 - 2013
        sub_title: Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at UdG-cutonala I have learned some technologies such as java, mysql, linux, information security, python.   I have learned the real value for a friendship I still keep my same friends since these times

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
